// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:0c26c275-87eb-45f6-ae4f-b0662afd2f38',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'aux-hosting-mobilehub-408829914',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1g9kf272iiuvr.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"aux-mobilehub-408829914-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-1","hashKey":"teamId","rangeKey":"personId"},{"tableName":"aux-mobilehub-408829914-tasks","attributes":[{"name":"userId","type":"S"},{"name":"taskId","type":"S"},{"name":"category","type":"S"},{"name":"created","type":"N"},{"name":"description","type":"S"}],"indexes":[{"indexName":"userId-created","hashKey":"userId","rangeKey":"created"}],"region":"us-east-1","hashKey":"userId","rangeKey":"taskId"}],
    'aws_mobile_analytics_app_id': 'e284520236684b0c8ac010e4e133e2c0',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'cc8d6a72-0670-4e02-b8a1-5025807206cf',
    'aws_project_name': 'aux-2018-02-07-09-26-00',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'aux-mobilehub-408829914',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'aux-userfiles-mobilehub-408829914',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_ytd6tneuW',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '63ij86svsdg0bio5nkt4unf3gb',
}

export default awsmobile;
